### ISSUE TITLE
Choose between first-match and best-match in CachePolicyNewForUser

### ISSUE THREAD

**Issue by vonhollen** [google/libpam-policycache#5]
The current CachePolicyNewForUser in [src/policy.c](../blob/master/src/policy.c) has to pick one section out of multiple possible matching sections. The current logic uses the first section it finds. Policy filenames are sorted before they are read.

@tokkee proposed an alternate way, picking the best match out of all possible matches. A section like `[user:janedoe]` would be picked before `[group:allusers]`. There's still the problem of ordering when multiple sections on the same level are chosen, but we can fallback to first-match between equal sections.

Why to choose first-match:
- Policy files can be more advanced.
- Figuring out what policy matches is more simple.
- The "disable=true" setting can blacklist certain users/groups before any other sections are tried.
- Netgroups can be preferred over groups.
- It's still required as a fallback in the best-match implementation.

Why to choose best-match:
- It's more intuitive. A `[user:janedoe]` section will always be picked for that user.
- It's more efficient. Querying large groups/netgroups can be very expensive, so it's nice to only do it when we know it's necessary.

What other pros/cons exist?

**Comment by smu-ggl** [comment]
Closing this. We didn't miss this improvement in 7 years.
